# On Controller Inventory Source configuration,
# the inventory filename needs to be filled manually,
# as it seems the Controller is not able to do that
# automatically, as it isually do for Templates
plugin: netbox.netbox.nb_inventory
api_endpoint: https://172.16.1.60
token: 196f73159c954796f75fdbeb6ffc88272749ac36
validate_certs: no
config_context: yes
group_by:
  - sites
  - device_types
  - manufacturers
