plugin: netbox.netbox.nb_inventory
api_endpoint: https://172.16.1.
token: 196f73159c954796f75fdbeb6ffc88272749ac36
validate_certs: no
config_context: yes
group_by:
  - sites
  - device_roles
  - manufacturers